download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile="household_power_consumption.zip",method="curl")
unzip("household_power_consumption.zip")
powconraw <- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
powcon <- powconraw[powconraw$Date=="1/2/2007" | powconraw$Date=="2/2/2007",]
powcon$Date <- as.Date(powcon$Date, format="%d/%m/%Y")
powcon$datetime <- as.POSIXct(paste(powcon$Date, powcon$Time), format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(powcon, plot(datetime,Global_active_power, type="l", ylab="Global Active Power (kilowatts)"))
with(powcon, plot(datetime,Voltage,type="l"))
with(powcon, plot(datetime,Sub_metering_1, type="l", ylab="Energy sub metering"))
with(powcon, lines(x=datetime,y=Sub_metering_2,col="red"))
with(powcon, lines(x=datetime,y=Sub_metering_3,col="blue"))
with(powcon, plot(datetime,Global_reactive_power,type="l"))
dev.copy(png,file="plot4.png")
dev.off()